
WITH POINT_OF_INTEREST_ADDRESSES_RELATIONSHIPS AS (
    SELECT * 
    FROM US_REAL_ESTATE.CYBERSYN.POINT_OF_INTEREST_ADDRESSES_RELATIONSHIPS
)
select * from POINT_OF_INTEREST_ADDRESSES_RELATIONSHIPS
